routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as'=>'home', 'uses'=>'HomeController']);


//Auth related routes starts
Route::get('login',['as'=>'login', 'uses'=>'AuthController@getLogin']);
Route::post('login', 'AuthController@postLogin');
Route::post('logout', ['as'=>'logout', 'uses'=>'AuthController@logout']);
Route::post('register',['as'=>'register', 'uses'=>'AuthController@register']);
//Auth related routes ends

Route::get('test',function (){
    //return view('pet.show');
});

Route::get('search',['as'=>'search','uses'=>'SearchController']);

//Profile related routes starts
Route::group(['middleware' => 'auth'], function(){
    Route::get('me', ['as'=>'profile.show', 'uses'=>'ProfileController@show']);
    Route::get('me/edit', ['as'=>'profile.edit', 'uses'=>'ProfileController@edit']);
    Route::post('me', ['as'=>'profile.update', 'uses'=>'ProfileController@update']);
});
//Profile related routes ends

//Pet related routes starts
Route::resource('pet', 'PetController', [
    'only' => [
        'create', 'store'
    ],
    'middleware' => 'auth'
]);
Route::get('pet', ['as'=>'pet.index', 'uses'=>'PetController@index']);
Route::get('pet/{pet}', ['as'=>'pet.show', 'uses'=>'PetController@show']);
//Pet related routes ends

resources/views/commons/_footer.blade.php
<footer class="basic-bg-color main">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center white">
                <p>© 2016 Anima</p>
                <p>| Direct | Pets for Sale and Adoption |</p>
                <p>| Sell and Buy Pets and Animals. All Rights Reserved. |</p>
            </div>
        </div>
    </div>
</footer>

resources/views/commons/_gmap-location-scripts.blade.php
<script async defer src="https://maps.googleapis.com/maps/api/js?key={{env('GOOGLE_GEO_KEY')}}&libraries=places&callback=initMap"></script>
<script type="text/javascript">
    function initMap() {
        var input = document.getElementById('location-autocomplete');
        var location = document.getElementById('geolocation-input');
        var autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.addListener('place_changed', function () {
            var place = autocomplete.getPlace();
            if (!place.geometry) {
                // User entered the name of a Place that was not suggested and
                // pressed the Enter key, or the Place Details request failed.
                window.alert("No details available for input: '" + place.name + "'");
                return;
            }

            var coordinates = place.geometry.location.lng()+','+place.geometry.location.lat();
            location.value = coordinates;
        });
    }
</script>

resources/views/commons/_main-nav.blade.php
<!--NAVIGATION-->
<nav class="navbar navbar-default fixed-navbar navigation sticky-navbar header-nav">
    <div class="container">
        <div class="navbar-header page-scroll">
            <a href="{{route('home')}}" class="navbar-brand brand-name">
                <img src="{{asset('assets/images/logo.png')}}" alt="logo" class="img-responsive brand-logo">
            </a>

            <button class="navbar-toggle nav-btn" data-toggle="collapse" data-target=".navHeaderCollapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <form id="logout" class="hidden" method="post" action="{{route('logout')}}">{{csrf_field()}}</form>

        <div class="collapse navbar-collapse navHeaderCollapse">
            <ul class="nav navbar-nav navbar-right lato light _18px header-main" id="menu">
                <li class="active "><a  href="{{route('home')}}">Home</a></li>
                @if(auth()->user())
                <li><a href="{{route('profile.show')}}">About Me</a></li>
                <li><a href="#" onclick="$('#logout').submit()">LOG OUT</a></li>
                <li><a href="{{route('pet.create')}}" id="post" class="basic-bg-color white">NEW POST</a></li>
                @else
                <li><a href="{{route('login')}}" id="login">LOG IN</a></li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/commons/_search.blade.php
<!--==========================

Start : Search

============================-->

<div class="search p-b-50 p-t-60 basic-bg-color">
    <div class="container">
        <div class="row">

            <!--search area-->
            <form action="{{route('search')}}" method="GET">
                <div class="col-xs-12 col-sm-10 m-b-15">
                    <div class="search-items-wrapper">
                        <div class="col-xs-12 col-sm-3 less-padding from-group s-m-b-15">
                            <select name="type_id" class="from-control defaultSelect text-capitalize type-selection">
                                <option value="">Animal Type</option>
                            </select>
                        </div>
                        <div class="col-xs-12 col-sm-3 less-padding from-group s-m-b-15">
                            <select name="breed_id" class="from-control defaultSelect text-capitalize breed-selection">
                                <option value="">Animal Breed</option>
                            </select>
                        </div>
                        <div class="col-xs-12 col-sm-3 less-padding from-group s-m-b-15">
                            <select name="sex" class="from-control defaultSelect text-capitalize sex-selection">
                                <option value="">Sex</option>
                                <option value="Male">Male</option>
                                <option value="Female">Female</option>
                            </select>
                        </div>

                        <div class="col-xs-12 col-sm-3 less-padding from-group s-m-b-15">
                            <button type="submit" class="search-btn">Find Your Pet</button>
                        </div>

                    </div>
                    <!-- /search-items-wrapper -->

                </div>
                <!-- /col-sm-10 -->
                {{--<div class="col-xs-12 col-sm-2 text-center">--}}

                    {{--<a href="#advanced-search" data-toggle="collapse" aria-expanded="false" aria-controls="advanced-search" role="button" class="white _16px advanced-search center-block">Advanced search <i class="fa fa-angle-down"></i></a>--}}

                {{--</div>--}}
                {{--<!-- /col-sm-2 -->--}}

                {{--<div id="advanced-search" class="collapse __web-inspector-hide-shortcut__" style="max-height: 97px;">--}}
                    {{--<div class="col-xs-12 col-sm-10">--}}
                        {{--<div class="search-items-wrapper">--}}
                            {{--<div class="col-xs-12 col-sm-3 less-padding from-group s-m-b-15">--}}
                                {{--<select name="property type" class="from-control defaultSelect text-capitalize">--}}
                                    {{--<option value="">Animal Type</option>--}}
                                    {{--<option value="">DOG</option>--}}
                                    {{--<option value="">tiger</option>--}}
                                    {{--<option value="">cat</option>--}}
                                    {{--<option value="">monkey</option>--}}
                                {{--</select>--}}
                            {{--</div>--}}
                            {{--<div class="col-xs-12 col-sm-3 less-padding from-group s-m-b-15">--}}
                                {{--<select name="property type" class="from-control defaultSelect text-capitalize">--}}
                                    {{--<option value="">Animal Type</option>--}}
                                    {{--<option value="">DOG</option>--}}
                                    {{--<option value="">tiger</option>--}}
                                    {{--<option value="">cat</option>--}}
                                    {{--<option value="">monkey</option>--}}
                                {{--</select>--}}
                            {{--</div>--}}
                            {{--<div class="col-xs-12 col-sm-3 less-padding from-group s-m-b-15">--}}
                                {{--<select name="property type" class="from-control defaultSelect text-capitalize">--}}
                                    {{--<option value="">Animal Type</option>--}}
                                    {{--<option value="">DOG</option>--}}
                                    {{--<option value="">tiger</option>--}}
                                    {{--<option value="">cat</option>--}}
                                    {{--<option value="">monkey</option>--}}
                                {{--</select>--}}
                            {{--</div>--}}

                            {{--<div class="col-xs-12 col-sm-3 less-padding from-group s-m-b-15">--}}
                                {{--<select name="property type" class="from-control defaultSelect text-capitalize">--}}
                                    {{--<option value="">Animal Type</option>--}}
                                    {{--<option value="">DOG</option>--}}
                                    {{--<option value="">tiger</option>--}}
                                    {{--<option value="">cat</option>--}}
                                    {{--<option value="">monkey</option>--}}
                                {{--</select>--}}
                            {{--</div>--}}

                        {{--</div>--}}
                        {{--<!-- /search-items-wrapper -->--}}

                    {{--</div>--}}
                    {{--<!-- /col-sm-10 -->--}}
                {{--</div>--}}
            </form>

        </div><!--/row-->
    </div>
</div>


<!--==========================
End : Search
============================-->

resources/views/commons/_type-loading-script.blade.php
<script>
    $(document).ready(function () {

        var types = {!! App\PetType::with('breeds')->get()->keyBy('id')->toJson() !!};

        var typesOpt = '';

        for(var i in types){
            typesOpt+= '<option value="'+types[i].id+'">'+types[i].title+'</option>';
        }

        $('.type-selection').append(typesOpt);

        $('.type-selection').change(function (e) {

            $('.type-selection').val(this.value);

            if(!this.value){
                return;
            }

            var breeds = types[this.value]['breeds'];

            var breedsOpt = '<option value="">Animal Breed</option>';

            for(var i in breeds){
                breedsOpt+= '<option value="'+breeds[i].id+'">'+breeds[i].title+'</option>';
            }
            $('.breed-selection').html(breedsOpt);
        });

        $('.breed-selection').change(function (e) {
            $('.breed-selection').val(this.value);
        });

        $('.sex-selection').change(function (e) {
            $('.sex-selection').val(this.value);
        });

        var urlParams = new URLSearchParams(window.location.search);
        $('.type-selection').val(urlParams.get('type_id')).change();
        $('.breed-selection').val(urlParams.get('breed_id')).change();
        $('.sex-selection').val(urlParams.get('sex')).change();
        var max_dist = urlParams.get('max_distance');
        var max_price = urlParams.get('max_price');
        if(max_dist){
            $('.input-range-1').val(max_dist).next('.range-value').html(max_dist+'miles');
        }
        if(max_price){
            $('.input-range-2').val(max_price).next('.range-value').html(urlParams.get('max_price')+'$');
        }
    })
</script>