routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as'=>'home', 'uses'=>'HomeController']);


//Auth related routes starts
Route::get('login',['as'=>'login', 'uses'=>'AuthController@getLogin']);
Route::post('login', 'AuthController@postLogin');
Route::post('logout', ['as'=>'logout', 'uses'=>'AuthController@logout']);
Route::post('register',['as'=>'register', 'uses'=>'AuthController@register']);
//Auth related routes ends

Route::get('test',function (){
    //return view('pet.show');
});

Route::get('search',['as'=>'search','uses'=>'SearchController']);

//Profile related routes starts
Route::group(['middleware' => 'auth'], function(){
    Route::get('me', ['as'=>'profile.show', 'uses'=>'ProfileController@show']);
    Route::get('me/edit', ['as'=>'profile.edit', 'uses'=>'ProfileController@edit']);
    Route::post('me', ['as'=>'profile.update', 'uses'=>'ProfileController@update']);
});
//Profile related routes ends

//Pet related routes starts
Route::resource('pet', 'PetController', [
    'only' => [
        'create', 'store'
    ],
    'middleware' => 'auth'
]);
Route::get('pet', ['as'=>'pet.index', 'uses'=>'PetController@index']);
Route::get('pet/{pet}', ['as'=>'pet.show', 'uses'=>'PetController@show']);
//Pet related routes ends

app/Pet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Storage;
use DB;

class Pet extends Model
{
    //We need mass assignment
    protected $fillable = ['name','breed_id','age','sex','color','price', 'location', 'location_string',
                            'location', 'description','image1','image2','image3'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function breed()
    {
        return $this->belongsTo('App\Breed');
    }

    public function type(){
        return $this->belongsTo('App\PetType');
    }


    // For Geospatial
    protected $geofields = array('location');


    public function setLocationAttribute($value) {
        $this->attributes['location'] = DB::raw("POINT($value)");
    }

    public function getLocationAttribute($value){

        $loc =  substr($value, 6);
        $loc = preg_replace('/[ ,]+/', ',', $loc, 1);

        return substr($loc,0,-1);
    }

    public function newQuery($excludeDeleted = true)
    {
        $raw='';
        foreach($this->geofields as $column){
            $raw .= ' astext('.$column.') as '.$column.' ';
        }

        return parent::newQuery($excludeDeleted)->addSelect('*',DB::raw($raw));
    }

    /**
     * @param $query
     * @param $dist_in_meter
     * @param $location
     * @return mixed
     */
    public function scopeDistance($query, $dist_in_meter, $location)
    {
        return $query->whereRaw('st_distance_sphere(location,POINT('.$location.')) < '.$dist_in_meter);
    }

    // For Geospatial Ends

    public function getImage1Attribute($path){
        if($path){
            return Storage::disk('user')->url($path);
        }
    }

    public function getImage2Attribute($path){
        if($path){
            return Storage::disk('user')->url($path);
        }
    }

    public function getImage3Attribute($path){
        if($path){
            return Storage::disk('user')->url($path);
        }
    }
}

app/PetType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PetType extends Model
{
    public $timestamps = false;

    public function breeds(){
        return $this->hasMany('App\Breed');
    }
}

app/Http/Controllers/PetController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePetRequest;
use App\Pet;
use App\PetType;
use Illuminate\Http\Request;

class PetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Pet $petM)
    {
        $pets = $petM->all(); //@todo paginate
        return view('pet.index',compact('pets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param PetType $petTypeM
     * @return \Illuminate\Http\Response
     */
    public function create(PetType $petTypeM)
    {
        $pet_types = $petTypeM->with('breeds')->get()->toArray();
        return view('pet.create', compact('pet_types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StorePetRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePetRequest $request)
    {
        $this->storeImages($request);
        $input = $this->getIntendedInput($request->all());
        $pet = auth()->user()->pets()->create($input);
        return redirect()->route('pet.show',[$pet->id]);
    }


    // Removes the prefix from the
    private function getIntendedInput($originalInput){
        $animal = str_slug(PetType::find($originalInput['animal_type'])->title,'_');

        $input = [];

        array_map(function($key,$value) use(&$input, $animal){
            if(strpos($key,$animal)!==false){
                $input[str_replace($animal.'_','',$key)]=$value;
            }else{
                $input[$key]=$value;
            }
        }, array_keys($originalInput),$originalInput);

        return $input;
    }


    /**
     * @param StorePetRequest $request
     */

    private function storeImages(StorePetRequest $request){
        for($i=1;$i<=3;$i++){
            if($request->hasFile("image_file_$i")){
                $path = $request->file("image_file_$i")
                                ->store(auth()->user()->id.'/pets',['disk'=>'user']);
                $request->merge(["image$i"=>$path]);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pet $pet
     * @return \Illuminate\Http\Response
     */
    public function show(Pet $pet)
    {
        $pet->load('user');
        $similar = $pet->inRandomOrder()->take(8)->get();
        return view('pet.show', compact('pet','similar'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pet  $pet
     * @return \Illuminate\Http\Response
     */
    public function edit(Pet $pet)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pet  $pet
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pet $pet)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pet  $pet
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pet $pet)
    {
        //
    }
}

resources/views/pet/_filters.blade.php
<div class="col-xs-12 col-sm-3 different-bg-color">
    <p class="_24px black s-text-center m-t-15">REFINE SEARCH</p>
    <form action="{{route('search',request()->all())}}" method="get">
        <p>Pet Type</p>
        <select name="type_id" class="select m-b-15 type-selection">
        </select>

        <p>Pet Breed</p>
        <select name="breed_id" class="select m-b-15 breed-selection">
        </select>

        {{--<p>Advert Type</p>--}}
        {{--<select name="" class="select m-b-15">--}}
            {{--<option value="">All advert type</option>--}}
            {{--<option value="">All advert type</option>--}}
            {{--<option value="">All advert type</option>--}}
            {{--<option value="">All advert type</option>--}}
        {{--</select>--}}

        <p>Location</p>
        <input type="text" name="location_str" id="location-autocomplete" class="text m-b-15" placeholder="Town of Postcord" value="{{ request()->get('location_str')}}">
        <input name="coordinates" id="geolocation-input" type="hidden" value="{{ request()->get('coordinates')}}">

        <p>Distance</p>
        <input type="range" name="max_distance" class="input-range-1" min="0" max="1000" step="10" value="0">
        <p class="range-value"></p>

        <p>Price</p>
        <input type="range" name="max_price" class="input-range-2" min="0" max="1000" step="10" value="0">
        <p class="range-value"></p>


        {{--<p>Key Word</p>--}}
        {{--<input type="text" class="text m-b-15" >--}}

        {{--<p>Result Per Page</p>--}}
        {{--<select name="" class="select m-b-15">--}}
            {{--<option value="">All advert type</option>--}}
            {{--<option value="">All advert type</option>--}}
            {{--<option value="">All advert type</option>--}}
            {{--<option value="">All advert type</option>--}}
        {{--</select>--}}

        <button type="submit" class="white bold basic-bg-color up-btn">UPDATE SEARCH</button>
    </form>
</div>
<!--Right Sight Box-->

resources/views/pet/_similar.blade.php
<!--=====================

Start : Similar pets

=======================-->



<div class="property p-b-50 p-t-60">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center m-b-50 s-m-b-15">
                <p class="bold _30px basic-color">SIMILAR PETS</p>
            </div>
            <div class="col-xs-12">
                <div class="property-item-container">
                    <div class="belt">
                        <div class="state state-1"><!--'.state-1'-->
                            @foreach($similar as $pet)
                            <!--1-->
                            <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-0 col-md-3 less-padding-2 s-m-b-15 m-b-5">
                                <div class="inner-box">
                                    <div class="img-container">
                                        <img src="{{$pet->image1}}" alt="" class="img-responsive">
                                    </div>
                                    <a href="{{route('pet.show', [$pet->id] )}}">
                                    <div class="search-icon text">
                                        <p class="white-10">{{$pet->description}}</p>
                                    </div>
                                    </a>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12 text-center">
                                        <p class="basic-color bold">{{$pet->price ? '$'.($pet->price+0) : ''}}</p>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </div><!--'.state-1'-->

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--===================

End:SIMILAR PETS

======================-->

resources/views/pet/create.blade.php
@extends('templates.main')

@push('styles')
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/plugins/fileinput.min.css')}}" media="all" />
@endpush


@section('content')
    <form method="post" action="{{route('pet.store')}}" enctype="multipart/form-data">
        {{csrf_field()}}
        <!--=================================
        image uplode
        ===================================-->
        <div class="main-container">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-sm-offset-3 page-content">
                        <div class="inner-box category-content">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-horizontal">
                                        <!--picture-->
                                        <div class="form-group">

                                            <div class="col-xs-12">
                                                <!--picture 1-->
                                                <div class="m-b-10">
                                                    <input name="image_file_1" id="input-upload-img1" type="file" class="file" data-preview-file-type="text" required>
                                                    @if($errors->has('image_file_1'))
                                                        <span class="text-danger">{{$errors->first('image_file_1')}}</span>
                                                    @endif
                                                </div>

                                                <!--picture 2-->
                                                <div class="m-b-10">
                                                    <input name="image_file_2" id="input-upload-img2" type="file" class="file" data-preview-file-type="text">
                                                    @if($errors->has('image_file_2'))
                                                        <span class="text-danger">{{$errors->first('image_file_2')}}</span>
                                                    @endif
                                                </div>

                                                <!--picture 3-->
                                                <div class="m-b-10">
                                                    <input name="image_file_3" id="input-upload-img3" type="file" class="file" data-preview-file-type="text">
                                                    @if($errors->has('image_file_3'))
                                                        <span class="text-danger">{{$errors->first('image_file_3')}}</span>
                                                    @endif
                                                </div>

                                                <p class="help-block">Add up to 3 photos. Use a real image of your
                                                    product, not catalogs.</p>

                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="item-form p-b-50 p-t-60">
            <div class="container">
                <div class="row">
                    <p class="basic-color _24px text-center bold">SELECT THE CATAGORY</p>
                </div>
                <div class="col-xs-12 col-sm-6 col-sm-offset-3">
                    <div class="form-group m-b-50">
                        <select name="animal_type" id="animal-select">
                            <option selected="selected" data-target="0"> SELECT HERE</option>
                            @foreach($pet_types as $i=>$type)
                            <option value="{{$type['id']}}" data-target="{{$i+1}}">{{strtoupper($type['title'])}}</option>
                            @endforeach
                        </select>

                        <input name="location_string" type="text" id="location-autocomplete" class="fill-form m-b-10" placeholder="Location">
                        <input name="location" id="geolocation-input" type="hidden">
                    </div>

                    @for($i=0,$l=sizeof($pet_types);$i<$l;$i++)
                        <div class="form-group same-all " data-index="{{$i+1}}">
                            <p class="black _18px m-b-30">FILL UP THE FORM FOR {{strtoupper($pet_types[$i]['title'])}}</p>
                            <input type="text" class="fill-form m-b-10" placeholder="Name" name="{{str_slug($pet_types[$i]['title'],'_')}}_name">
                            <select name="{{str_slug($pet_types[$i]['title'],'_')}}_breed_id" class="fill-form m-b-10" required>
                                @foreach($pet_types[$i]['breeds'] as $breed)
                                <option value="{{$breed['id']}}" >{{$breed['title']}}</option>
                                @endforeach
                            </select>
                            <input type="number" class="fill-form m-b-10" placeholder="Price" name="{{str_slug($pet_types[$i]['title'],'_')}}_price" step="any">
                            <textarea name="{{str_slug($pet_types[$i]['title'],'_')}}_description" placeholder="Description"></textarea>
                            <input type="text" class="fill-form m-b-10" placeholder="Age" name="{{str_slug($pet_types[$i]['title'],'_')}}_age">
                            <input type="text" class="fill-form m-b-10" placeholder="Sex" name="{{str_slug($pet_types[$i]['title'],'_')}}_sex">
                            <input type="text" class="fill-form m-b-10" placeholder="Colour" name="{{str_slug($pet_types[$i]['title'],'_')}}_color">
                            <button type="submit" class="basic-bg-color white fill-btn">SUBMIT</button>
                        </div>
                    @endfor
                </div>
            </div>
        </div>
    </form>
@endsection

@push('scripts')
<script src="{{asset('assets/js/plugins/fileinput.min.js')}}" type="text/javascript"></script>
<script>
    // initialize with defaults
    $("#input-upload-img1").fileinput();
    $("#input-upload-img2").fileinput();
    $("#input-upload-img3").fileinput();
</script>
@include('commons._gmap-location-scripts')
@endpush

resources/views/pet/index.blade.php
@extends('templates.main')

@push('styles')
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/plugins/range.css')}}" media="all" />
@endpush

@section('content')

    @include('commons._search')

    <!--===================
	Start : Listing
	=====================-->

    <div class="listing p-b-10 p-t-10">
        <div class="container">
            <div class="row">

                @include('pet._filters')

                <div class="col-xs-12 col-sm-9">
                    <div class="row m-b-15 m-t-15">
                        <div class="col-xs-12 col-sm-9">
                            <p class="bold black _24px">PETS Found{{$location? " near $location":""}}</p>
                            <p>101 Dogs found in sydney</p>
                        </div>
                        <div class="col-xs-12 col-sm-3">
                            <p >SORT BY :</p>
                            <form action="#" method="POST">
                                <select name="sortBy" id="sortBy">
                                    <option value="">Date update(Newest)</option>
                                    <option value="">Date update(Newest)</option>
                                    <option value="">Date update(Newest)</option>
                                    <option value="">Date update(Newest)</option>
                                </select>
                            </form>
                        </div>

                    </div>
                    @foreach($pets as $pet)
                    <!--row-->
                    <div class="row whole-wrapper m-b-15">
                        <div class="col-xs-10 col-xs-offset-1 col-sm-3 col-sm-offset-0">
                            <div class="pet-image-wrapper">
                                <a href="{{route('pet.show',[$pet->id])}}"><img src="{{$pet->image1}}" alt="" class="img-responsive"></a>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-7">
                            <div class="blog-wrapper">
                                <p class="_30px bold black f-r">{{$pet->price ? '$'.($pet->price+0) : ''}}</p>
                                <p class="bold _24px basic-color"><a class="basic-color" href="{{route('pet.show',[$pet->id])}}">{{$pet->name}}</a></p>
                                @if($pet->location_string)
                                <p class="black regular"><i class="fa fa-map-marker m-r-10"></i><span>{{$pet->location_string}}</span></p>
                                @endif
                                <p>{!! nl2br($pet->description) !!}</p>

                                <p class="m-t-30"><i class="fa fa-clock-o m-r-10" aria-hidden="true"></i><span>{{$pet->created_at->diffForHumans()}}</span></p>
                            </div>
                        </div>

                    </div>
                    <!--/row-->
                    @endforeach

                </div>



                <div class="col-xs-12 col-sm-3">
                    <div class="row m-b-15">
                        <div class="col-sm-12 visible-xs">
                            <div class="wrapper-inner">
                                <p class="_24px basic-color"> SORT BY :</p>

                                <ul class="list-unstyled black _20px">
                                    <li><a href="#">Newly Listed</a></li>
                                    <li><a href="#">Lower Price</a></li>
                                    <li><a href="#">First Higher</a></li>
                                    <li><a href="#">Price First</a></li>

                                </ul>
                            </div>

                        </div>
                    </div>

                    <div class="row m-b-15">
                        <div class="col-sm-12 visible-xs">
                            <div class="wrapper-inner">
                                <p class="_24px basic-color"> Refine by Price</p>

                                <ul class="list-unstyled black _20px">
                                    <li><a href="#">All categories</a></li>
                                    <li><a href="#">Fish</a></li>
                                    <li><a href="#">Cats</a></li>
                                    <li><a href="#">Dogs</a></li>
                                    <li><a href="#">Birds</a></li>
                                    <li><a href="#">Horses</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-12 visible-xs">
                            <div class="wrapper-inner">
                                <p class="_24px basic-color"> Your Cheappest Pet Supplies Store</p>

                                <div class="row">
                                    <div class="col-xs-10 col-xs-offset-1">
                                        <img src="{{assert('assets/images/dog/ecommerce.png')}}" alt="" class="img-responsive">
                                    </div>
                                </div>
                                <div class="row">
                                    <a href="" id="post" class="_20px basic-bg-color text-uppercase text-center">CLICK HERE</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>


    <!--===================
    End : Listing
    =====================-->

@endsection

@push('scripts')
<script src="{{asset('assets/js/plugins/jquery.zoom.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/js/plugins/mag.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/js/plugins/range.js')}}" type="text/javascript"></script>
@include('commons._type-loading-script')
@include('commons._gmap-location-scripts')
@endpush